CREATE TABLE IF NOT EXISTS Cliente(
	id SERIAL NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	cpf CHAR(11) NOT NULL,
	nascimento DATE NOT NULL,
	email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Divida(
	id SERIAL NOT NULL PRIMARY KEY,
	situacao BOOL 
);
